In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import alpaca_trade_api as tradeapi


%matplotlib inline

In [3]:
from dotenv import load_dotenv
load_dotenv()

# Set Alpaca API key and secret
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

api = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version = "v2"
)

In [13]:
tickers1 = ['GCCHX', 'SPYX', 'ESGD']
tickers2 = ['CTEC', 'CRBN', 'EFAX']
tickers3 = ['ETHO', 'FAN']

# These are the tickers we discussed that have data that can be pulled from Alapaca. I havent tried other API's yet. 
tickersfin = ['SPYX', 'ESGD', 'CRBN', 'EFAX', 'ETHO', 'FAN']

timeframe = "1D"

# Pulling just a year for now to ensure they have usable data: 
start_date = pd.Timestamp("2019-05-04", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2020-05-04", tz="America/New_York").isoformat()

# Ignore 
esg_data1 = api.get_barset(
    tickers1,
    timeframe,
    start=start_date,
    end=end_date
).df

# ignore 
esg_data2 = api.get_barset(
    tickers2,
    timeframe,
    start=start_date,
    end=end_date
).df

# ignore 
esg_data3 = api.get_barset(
    tickers3,
    timeframe,
    start=start_date,
    end=end_date
).df

# Here is the API call for the working tickers: 
esg_datafin = api.get_barset(
    tickersfin,
    timeframe,
    start=start_date,
    end=end_date
).df



# esg_data1.tail(10)
esg_datafin.tail(10)

                               CRBN                                         \
                               open      high       low     close   volume
time
2020-04-21 00:00:00-04:00  107.6200  108.0800  106.1391  106.2700  11174.0
2020-04-22 00:00:00-04:00  108.5400  108.9400  107.9000  108.7300  41970.0
2020-04-23 00:00:00-04:00  109.7000  110.2547  108.6100  108.6100  12192.0
2020-04-24 00:00:00-04:00  109.2800  109.8790  108.5300  109.8790   7454.0
2020-04-27 00:00:00-04:00  110.7400  111.7400  110.7162  111.7400   9310.0
2020-04-28 00:00:00-04:00  112.9884  113.1300  111.5900  111.5900   5720.0
2020-04-29 00:00:00-04:00  113.8100  114.7400  113.8100  114.6958   9516.0
2020-04-30 00:00:00-04:00  113.7000  113.7000  112.5973  112.8100  26932.0
2020-05-01 00:00:00-04:00  110.8200  110.8994  109.6750  109.8050   6942.0
2020-05-04 00:00:00-04:00  109.0800  110.2400  109.0800  110.2400  27094.0

                              EFAX                                      ...  \
                              open     high      low    close   volume  ...
time                                                                    ...
2020-04-21 00:00:00-04:00  57.6900  57.6900  57.0833  57.0833   6179.0  ...
2020-04-22 00:00:00-04:00  57.8300  58.1555  57.8233  57.8233   1374.0  ...
2020-04-23 00:00:00-04:00  57.8280  58.0684  57.7378  57.7841   2594.0  ...
2020-04-24 00:00:00-04:00  57.9900  58.2892  57.9900  58.2892   2886.0  ...
2020-04-27 00:00:00-04:00  59.0770  59.1490  59.0770  59.1481   1721.0  ...
2020-04-28 00:00:00-04:00  60.1596  60.1596  59.8910  60.0790   2031.0  ...
2020-04-29 00:00:00-04:00  60.6500  61.3800  60.6500  61.3800   2223.0  ...
2020-04-30 00:00:00-04:00  60.5600  60.5600  59.5900  60.0100  17857.0  ...
2020-05-01 00:00:00-04:00  59.1000  59.1000  58.5650  58.5650    997.0  ...
2020-05-04 00:00:00-04:00      NaN      NaN      NaN      NaN      NaN  ...

                             FAN                                    SPYX  \
                            open     high      low   close volume   open
time
2020-04-21 00:00:00-04:00  12.01  12.1650  12.0000  12.040  14606  68.90
2020-04-22 00:00:00-04:00  12.22  12.2200  12.1200  12.190  16112  68.91
2020-04-23 00:00:00-04:00  12.28  12.3515  12.1300  12.140  13115  69.71
2020-04-24 00:00:00-04:00  12.26  12.2600  12.1350  12.230  12335  69.71
2020-04-27 00:00:00-04:00  12.34  12.4800  12.2800  12.480  13556  70.49
2020-04-28 00:00:00-04:00  12.65  12.7100  12.5500  12.565  11063  71.95
2020-04-29 00:00:00-04:00  12.75  12.8800  12.7300  12.800  14082  71.83
2020-04-30 00:00:00-04:00  12.71  12.7100  12.5114  12.589  22010  72.43
2020-05-01 00:00:00-04:00  12.43  12.4300  12.3000  12.340  24373  70.36
2020-05-04 00:00:00-04:00  12.23  12.3050  12.2001  12.290  19682  69.66


                              high      low    close    volume
time
2020-04-21 00:00:00-04:00  68.9000  67.4000  67.7000  101842.0
2020-04-22 00:00:00-04:00  70.0148  68.5544  69.2800  147328.0
2020-04-23 00:00:00-04:00  70.1024  69.0110  69.0300  164710.0
2020-04-24 00:00:00-04:00  70.1200  68.9300  69.8900   38706.0
2020-04-27 00:00:00-04:00  71.1833  70.4846  71.0500   38696.0
2020-04-28 00:00:00-04:00  71.9500  70.5800  70.5990   70974.0
2020-04-29 00:00:00-04:00  72.8300  71.7801  72.4600  207820.0
2020-04-30 00:00:00-04:00  72.4300  71.2700  71.7600  220276.0
2020-05-01 00:00:00-04:00  70.3600  69.5501  69.7101  207072.0
2020-05-04 00:00:00-04:00  70.0500  68.9600  70.0000   75378.0

[10 rows x 30 columns]

In [15]:
# Basic data 
esg_datafin.describe()

             CRBN                                                     \
             open        high         low       close         volume
count  251.000000  251.000000  251.000000  251.000000     251.000000
mean   119.841209  120.351851  119.311854  119.855503   15756.741036
std      8.740462    8.408922    9.095203    8.758717   31077.826119
min     90.880000   91.000000   87.450000   89.440000     378.000000
25%    116.445000  116.960000  115.900000  116.715000    5341.500000
50%    120.750000  121.090000  120.175000  120.480000    8215.000000
75%    125.955000  126.155000  125.494800  125.780000   14627.500000
max    133.650000  133.840000  133.526100  133.716600  434414.000000

             EFAX                                                    ...  \
             open        high         low       close        volume  ...
count  227.000000  227.000000  227.000000  227.000000    227.000000  ...
mean    66.814712   67.020247   66.664976   66.843326   5250.017621  ...
std      5.557761    5.400142    5.680236    5.567873  11591.453879  ...
min     49.690000   49.970000   49.200000   49.250000    100.000000  ...
25%     65.359550   65.478300   65.348550   65.369550    897.500000  ...
50%     67.753000   67.830000   67.730000   67.748000   1990.000000  ...
75%     71.170000   71.240000   70.997300   71.077000   4547.000000  ...
max     73.350000   73.470000   73.350000   73.420000  94442.000000  ...

              FAN                                                     \
             open        high         low       close         volume
count  252.000000  252.000000  252.000000  252.000000     252.000000
mean    13.460910   13.521625   13.388493   13.457207   36981.678571
std      0.982806    0.959975    1.009804    0.986056   42768.319137
min     10.580000   10.590000   10.170000   10.230000     660.000000
25%     12.837450   12.890000   12.807500   12.870525   13697.750000
50%     13.425000   13.460000   13.400000   13.422300   22949.500000
75%     14.002500   14.137500   13.977500   14.025000   40280.500000
max     15.660000   15.680000   15.610000   15.665000  325956.000000

             SPYX
             open        high         low       close         volume
count  251.000000  251.000000  251.000000  251.000000     251.000000
mean    73.140516   73.638828   72.628592   73.061403   33820.828685
std      5.100265    5.035958    5.337572    5.095822   43378.127372
min     57.130000   57.130000   54.300000   55.585000     248.000000
25%     70.435000   70.700000   69.897600   70.275000    8824.500000
50%     72.880000   73.190000   72.498700   72.800000   17373.000000
75%     76.510000   77.027800   76.210050   76.545000   38701.000000
max     83.230000   91.845000   83.190000   83.207000  248066.000000

[8 rows x 30 columns]